### PR TITLE
Feat/dev 40 assign default project creation

### PR DESCRIPTION
**Pull request by XukunXiangUChicago**
add the `_defaults` property to store the `property_name: default value` information for psqlgraph to pick up

### CODE REVIEW

**Review by kulgan — COMMENTED** [review]
Looks good, but can you update the psqlgraph pin on this branch to point to the psqlgraph branch with the dependent changes

**Comment by XukunXiangUChicago** [comment]
still working on the psqlgraph dependency, not able to merge just yet

**Review by ProfOak — APPROVED** [review]
Approving assuming we merge, and tag the change in https://github.com/NCI-GDC/psqlgraph/pull/196, then bump the pin in this pr. :shipit:

**Review by kulgan — APPROVED** [review]

**Comment by XukunXiangUChicago** [comment]
It might be better to wait for [the psqlgraph fix](https://github.com/NCI-GDC/psqlgraph/pull/197) merged first and pin that new tag before merging this one

**Pull request merged**
