### PR TITLE
feat(tasks): add RunnerTask model

### PR DESCRIPTION
**Pull request by millerjs**
Create a RunnerTask model to hold scheduled tasks for runners.

```
 id | node_id | runner_type | created
----+---------+-------------+---------
```

r? @philloooo @christiandompierre

### CODE REVIEW

**Comment by dankolbman** [comment]
So the idea is that we will have a table full of rows of nodes with a task that needs to be run on them? What if we have an operation that needs to be done on all filenodes, or some big number of nodes? I think this table would get out of hand really quickly. It seems like using postgres may not be the best way to queue tasks?

**Comment by dankolbman** [comment]
I know this is probably a short term solution, but we should probably look into setting up celery or redis to handle runners and future import and processing functionality.

**Comment by millerjs** [comment]
Agreed. The solution to large jobs is to schedule them in batches. We can add a new persistence store but every time we do this, the operational cost of maintenance goes up.  This is just the model for _one_ proposed solution of many

**Comment by millerjs** [comment]
This solution generally seems like a bad idea if for no reason that it relie on under-performant table locks

**Pull request closed without merging**
